import Head from 'next/head'
import { getPosts } from '../services/index'
import { PostCard, PostWidget, Categories } from '../components'
import { FeaturedPosts } from '../sections';


export default function Home({ posts }) {
  return (
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>BlogSpot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts title= "Featured Posts" />
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {
            posts.posts.data.map((post) => <PostCard post={post} key={post.id} />)
          }
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget slug={posts.id} />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const posts = await getPosts() || [];
  return {
    props: {
      posts
    },
  }
}
// 10.70.91.21